pipeline{
    agent any
    tools {nodejs "node"}

    stages {
        stage('Build Maven') {
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: '	github-user', url: 'https://github.com/johnnycashash/kubernetes-demo.git']]])
                   sh '''
                      cd my-shopping-app
                      npm run build
                      '''

            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                  sh '''
                     cd my-shopping-app
                     docker build -t jagansingh/my-shopping-app .
                     '''
                }
            }
        }
        stage('Deploy Docker Image') {
            steps {
                script {
                 withCredentials([string(credentialsId: 'dockerhub-pwd', variable: 'dockerhubpwd')]) {
                    sh 'docker login -u jagansingh -p ${dockerhubpwd}'
                 }
                 sh '''
                    cd my-shopping-app
                    docker push jagansingh/my-shopping-app:latest
                    '''
                }
            }
        }
    }
}
