apiVersion: v1
kind: Service
metadata:
  name: product-mysql
  labels:
    app: product
spec:
  ports:
    - port: 3306
  selector:
    app: product
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: product
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-mysql
  labels:
    app: product
spec:
  selector:
    matchLabels:
      app: product
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: product
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: PASSWORD
        - name: MYSQL_DATABASE
          value: "product"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE product (id int(11) NOT NULL AUTO_INCREMENT, name varchar(512) CHARACTER SET utf8 DEFAULT NULL, price int(11) DEFAULT NULL, product_id varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, PRIMARY KEY ('id')) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
    INSERT INTO product (name, price, product_id) VALUES ('JUST SOME ITEM', 32000, '_vHjnksjdvDSjjLlkdk');
